# Generated by Django 4.0.4 on 2022-05-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_prato_delete_cardapio'),
        ('nutricional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricional',
            name='prato',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cardapio.prato'),
        ),
    ]
