# Generated by Django 4.0.4 on 2022-05-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricional', '0002_nutricional_prato'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricional',
            name='proteinas',
            field=models.DecimalField(decimal_places=1, default=60, max_digits=4),
            preserve_default=False,
        ),
    ]
