# Generated by Django 4.0.4 on 2022-05-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('valor', models.FloatField()),
                ('detalhes', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pratos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Cardapio',
        ),
    ]
